// <auto-generated />
using HypixelStatsBot.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HypixelStatsBot.Migrations
{
    [DbContext(typeof(PlayerStorage))]
    partial class PlayerStorageModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("HypixelStatsBot.Database.AccountData", b =>
                {
                    b.Property<int>("EntryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiscordID")
                        .HasColumnType("TEXT");

                    b.Property<string>("IGN")
                        .HasColumnType("TEXT");

                    b.HasKey("EntryID");

                    b.ToTable("AccountData");
                });
#pragma warning restore 612, 618
        }
    }
}
